name: Training Model

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  train:
    runs-on: ubuntu-latest
    environment: WANDB_API

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Access env
      run : echo "env load"
      env:
        WANDB_API: ${{ secrets.api }}
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create '/models' directory for saving model
      run: mkdir -p ./models/ 

    - name: Log in to W&B
      run: wandb login

    - name: Train the model
      run: python train.py
